export const CATEGORY_LINKS = {
  ALL: "/products",
  MEN: "/products?gender=Men",
  WOMEN: "/products?gender=Women",
  UNISEX: "/products?gender=Unisex",
  ACCESSORIES: "/products?gender=accessories",
};

export const FILTER_DATA = {
  gender: [
    { name: "Unisex", count: 46 },
    { name: "Women", count: 120 },
    { name: "Men", count: 111 },
    { name: "Boys", count: 18 },
    { name: "Girls", count: 13 },
  ],
  brands: [
    { name: "DKNY", count: 9 },
    { name: "EthnoVogue", count: 2 },
    { name: "SPYKAR", count: 14 },
    { name: "Raymond", count: 6 },
    { name: "Parx", count: 34 },
    { name: "SHOWOFF", count: 1 },
    { name: "Kenneth Cole", count: 1 },
    { name: "Police", count: 1 },
    { name: "Vishudh", count: 2 },
    { name: "Being Human", count: 1 },
    { name: "Homesake", count: 7 },
    { name: "SEJ by Nisha Gupta", count: 15 },
    { name: "YAK YAK", count: 1 },
    { name: "PARFAIT", count: 23 },
    { name: "Michael Kors", count: 3 },
    { name: "HIGHLANDER", count: 7 },
    { name: "JEWEL JUNCTION", count: 11 },
    { name: "ID", count: 13 },
    { name: "Story@home", count: 8 },
    { name: "Gini and Jony", count: 19 },
    { name: "Sera", count: 4 },
    { name: "AccessHer", count: 6 },
    { name: "Alcis", count: 1 },
    { name: "Difference of Opinion", count: 5 },
    { name: "Tokyo Talkies", count: 5 },
    { name: "ANNA SUI", count: 1 },
    { name: "her by invictus", count: 7 },
    { name: "Soie", count: 3 },
    { name: "Lara Karen", count: 1 },
    { name: "Urban Dog", count: 6 },
    { name: "ahilya", count: 4 },
    { name: "VASTRAMAY", count: 2 },
    { name: "Campus Sutra", count: 7 },
    { name: "FIDO DIDO", count: 2 },
    { name: "MIAH Decor", count: 5 },
    { name: "BuckleUp", count: 3 },
    { name: "Peter England", count: 1 },
    { name: "AIGNER", count: 1 },
    { name: "Lady Lyka", count: 9 },
    { name: "Park Avenue", count: 2 },
    { name: "Roadster", count: 1 },
    { name: "U.S. Polo Assn. Denim Co.", count: 1 },
    { name: "Sweet Dreams", count: 1 },
    { name: "Kazo", count: 2 },
    { name: "Stylo Bug", count: 1 },
    { name: "Bvlgari", count: 7 },
    { name: "Qraa Men", count: 1 },
    { name: "GAS", count: 1 },
    { name: "WITH", count: 2 },
    { name: "ZUSH", count: 2 },
    { name: "JBN Creation", count: 1 },
    { name: "U.S. Polo Assn. Kids", count: 2 },
    { name: "DressBerry", count: 1 },
    { name: "ColorPlus", count: 1 },
    { name: "Lakme", count: 5 },
    { name: "Allen Solly Woman", count: 1 },
    { name: "Palm Tree", count: 4 },
    { name: "Arrow", count: 1 },
    { name: "DAVID BECKHAM", count: 1 },
    { name: "MANGO", count: 1 },
    { name: "Carrera", count: 2 },
    { name: "ROMEE", count: 1 },
    { name: "TAYHAA", count: 1 },
    { name: "Ishin", count: 1 },
    { name: "Shoe Couture", count: 1 },
    { name: "HARBORNBAY", count: 2 },
    { name: "Keds", count: 1 },
    { name: "Rozia", count: 1 },
    { name: "Aj DEZInES", count: 2 },
    { name: "Monte Carlo", count: 1 },
    { name: "even", count: 1 },
    { name: "ether", count: 1 },
    { name: "Crimsoune Club", count: 1 },
    { name: "Russell Athletic", count: 1 },
    { name: "MIMOSA", count: 1 },
  ],
  // colors: [
  //   { name: "Black", count: 30308 },
  //   { name: "White", count: 22504 },
  //   // ... other colors
  // ],
  // priceRange: { min: 100, max: 10100 },
};
