export const CATEGORY_LINKS = {
  ALL: "/products",
  MEN: "/products?gender=Men",
  WOMEN: "/products?gender=Women",
  UNISEX: "/products?gender=Unisex",
  ACCESSORIES: "/products?gender=accessories",
};

export const FILTER_DATA = {
  gender: {
    isExpanded: false,
    options: [
      { name: "Unisex", count: 46, isChecked: false },
      { name: "Women", count: 120, isChecked: false },
      { name: "Men", count: 111, isChecked: false },
      { name: "Boys", count: 18, isChecked: false },
      { name: "Girls", count: 13, isChecked: false },
    ],
  },
  brands: {
    isExpanded: false,
    options: [
      { name: "DKNY", count: 9, isChecked: false },
      { name: "EthnoVogue", count: 2, isChecked: false },
      { name: "SPYKAR", count: 14, isChecked: false },
      { name: "Raymond", count: 6, isChecked: false },
      { name: "Parx", count: 34, isChecked: false },
      { name: "SHOWOFF", count: 1, isChecked: false },
      { name: "Kenneth Cole", count: 1, isChecked: false },
      { name: "Police", count: 1, isChecked: false },
      { name: "Vishudh", count: 2, isChecked: false },
      { name: "Being Human", count: 1, isChecked: false },
      { name: "Homesake", count: 7, isChecked: false },
      { name: "SEJ by Nisha Gupta", count: 15, isChecked: false },
      { name: "YAK YAK", count: 1, isChecked: false },
      { name: "PARFAIT", count: 23, isChecked: false },
      { name: "Michael Kors", count: 3, isChecked: false },
      { name: "HIGHLANDER", count: 7, isChecked: false },
      { name: "JEWEL JUNCTION", count: 11, isChecked: false },
      { name: "ID", count: 13, isChecked: false },
      { name: "Story@home", count: 8, isChecked: false },
      { name: "Gini and Jony", count: 19, isChecked: false },
      { name: "Sera", count: 4, isChecked: false },
      { name: "AccessHer", count: 6, isChecked: false },
      { name: "Alcis", count: 1, isChecked: false },
      { name: "Difference of Opinion", count: 5, isChecked: false },
      { name: "Tokyo Talkies", count: 5, isChecked: false },
      { name: "ANNA SUI", count: 1, isChecked: false },
      { name: "her by invictus", count: 7, isChecked: false },
      { name: "Soie", count: 3, isChecked: false },
      { name: "Lara Karen", count: 1, isChecked: false },
      { name: "Urban Dog", count: 6, isChecked: false },
      { name: "ahilya", count: 4, isChecked: false },
      { name: "VASTRAMAY", count: 2, isChecked: false },
      { name: "Campus Sutra", count: 7, isChecked: false },
      { name: "FIDO DIDO", count: 2, isChecked: false },
      { name: "MIAH Decor", count: 5, isChecked: false },
      { name: "BuckleUp", count: 3, isChecked: false },
      { name: "Peter England", count: 1, isChecked: false },
      { name: "AIGNER", count: 1, isChecked: false },
      { name: "Lady Lyka", count: 9, isChecked: false },
      { name: "Park Avenue", count: 2, isChecked: false },
      { name: "Roadster", count: 1, isChecked: false },
      { name: "U.S. Polo Assn. Denim Co.", count: 1, isChecked: false },
      { name: "Sweet Dreams", count: 1, isChecked: false },
      { name: "Kazo", count: 2, isChecked: false },
      { name: "Stylo Bug", count: 1, isChecked: false },
      { name: "Bvlgari", count: 7, isChecked: false },
      { name: "Qraa Men", count: 1, isChecked: false },
      { name: "GAS", count: 1, isChecked: false },
      { name: "WITH", count: 2, isChecked: false },
      { name: "ZUSH", count: 2, isChecked: false },
      { name: "JBN Creation", count: 1, isChecked: false },
      { name: "U.S. Polo Assn. Kids", count: 2, isChecked: false },
      { name: "DressBerry", count: 1, isChecked: false },
      { name: "ColorPlus", count: 1, isChecked: false },
      { name: "Lakme", count: 5, isChecked: false },
      { name: "Allen Solly Woman", count: 1, isChecked: false },
      { name: "Palm Tree", count: 4, isChecked: false },
      { name: "Arrow", count: 1, isChecked: false },
      { name: "DAVID BECKHAM", count: 1, isChecked: false },
      { name: "MANGO", count: 1, isChecked: false },
      { name: "Carrera", count: 2, isChecked: false },
      { name: "ROMEE", count: 1, isChecked: false },
      { name: "TAYHAA", count: 1, isChecked: false },
      { name: "Ishin", count: 1, isChecked: false },
      { name: "Shoe Couture", count: 1, isChecked: false },
      { name: "HARBORNBAY", count: 2, isChecked: false },
      { name: "Keds", count: 1, isChecked: false },
      { name: "Rozia", count: 1, isChecked: false },
      { name: "Aj DEZInES", count: 2, isChecked: false },
      { name: "Monte Carlo", count: 1, isChecked: false },
      { name: "even", count: 1, isChecked: false },
      { name: "ether", count: 1, isChecked: false },
      { name: "Crimsoune Club", count: 1, isChecked: false },
      { name: "Russell Athletic", count: 1, isChecked: false },
      { name: "MIMOSA", count: 1, isChecked: false },
    ],
  },
};
