import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/sonner"

const assistant = Assistant({ variable: "--font-assistant", subsets: ['latin'], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: "Fashion Town",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${assistant.variable} antialiased`}
      >
        <Nav />
        <div className="mt-[76px]">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
